### ISSUE TITLE
Working with multipart/form-data

### ISSUE THREAD

**Issue by zAlweNy26** [samchungy/fastify-zod-openapi#109]
How can I make the type correctly appear in swagger? Before using this plugin the `isFile` key from `@fastify/multipart` was working just fine. 
I'd like to know if this is something that can be directly added here or I must stay with this workaround I did:
```typescript
body: z.object({
    file: z.string().refine(s => Buffer.isBuffer(Buffer.from(s))).openapi({ format: 'binary' }),
})
```
It's a bit ugly but it works.

**Comment by samchungy** [comment]
Yeah that or z.preprocess would be the workaround

**Comment by samchungy** [comment]
> How can I make the type correctly appear in swagger? Before using this plugin the `isFile` key from `@fastify/multipart` was working just fine. I'd like to know if this is something that can be directly added here or I must stay with this workaround I did:
> 
> ```ts
> body: z.object({
>     file: z.string().refine(s => Buffer.isBuffer(Buffer.from(s))).openapi({ format: 'binary' }),
> })
> ```
> 
> It's a bit ugly but it works.

You might be able to go: 

`z.instanceof(Buffer).openapi({ type: 'string', format: 'binary'})`

**Comment by zAlweNy26** [comment]
Oh wow I didn't know that! Thanks, I'll close the issue then.

**Comment by paularmstrong** [comment]
In my setup, the file upload is not a Buffer at this point. I'm seeing a `@fastify/busboy` `FileStream` object, which is not exported. The only way to get around this that I'm finding to get around this is to blindly accept the input 😒 


```ts
body: z.object({
    file: z
      .custom(() => true)
      .openapi({ type: 'string', format: 'binary' }),
}),
```

Notes:
- The `FileStream` claims to _inherit_ from `Stream`, but `inherits()` doesn't seem to make it available for comparison with `z.instanceof(Stream)`: https://github.com/fastify/busboy/blob/e62384c9623ff9e7a72f5aca6817ca85fc10e31e/lib/types/multipart.js#L302 because it's not an _instance_ of a Stream, it has just inherited the prototype.

**Comment by Farnsi** [comment]
Can somebody give me an working example of an upload with fastify-zod-openapi and @fastify/multipart?

I can upload with axios and use @fastify/multipart on the server. But as soon as I use a route with schema validation, it fail, zodError, "FST_ERR_VALIDATION"

**Comment by Farnsi** [comment]
Solved it, i forgot to set `{ attachFieldsToBody: true }` when register @fastify/multipart. [Parse all fields and assign them to the body](https://github.com/fastify/fastify-multipart?tab=readme-ov-file#parse-all-fields-and-assign-them-to-the-body)
